pal = list("black" =  "#000000",
          "cyan_bluish_gray" =  "#abb8c3",
          "white" =  "#FFF",
          "pale_pink" =  "#f78da7",
          "vivid_red" = "#cf2e2e",
          "luminous_vivid_orange" =  "#ff6900",
          "luminous_vivid_amber" =  "#fcb900",
          "light_green_cyan" =  "#7bdcb5",
          "vivid_green_cyan" =  "#00d084",
          "pale_cyan_blue" =  "#8ed1fc",
          "vivid_cyan_blue" =  "#0693e3",
          "vivid_purple" =  "#9b51e0",
          "teal" =  '#10626f',
          "access_purple" =  "#270075",
          "highlighter_yellow" =  "#FFF800",
          "off_white" =  "#F9F9F9",
          "light_gray" =  "#979797"
)
